Clean registry cache
SUSE/rmt pull request #1143
Opened 2024-05-06 11:47 UTC by jesusbv

## Description

Clean the registry cache for the system getting deregistered

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [X] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [X] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [X] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [X] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

2024-05-06 11:47 UTC, jesusbv commented
Please, merge when #1142 has been reviewed + merged

2024-05-06 19:06 UTC, rjschwei requested changes

2024-05-07 21:24 UTC, bear454 commented on engines/registry/lib/registry/engine.rb
> +      end
Don't forget to adapt this to use the variables instead of reading the cache file!

2024-05-09 17:32 UTC, bear454 approved these changes

2024-05-09 17:43 UTC, rjschwei approved these changes

2024-05-09 17:43 UTC, merged