Add cloud-provider at creation time
SUSE/rmt pull request #570
Opened 2020-06-05 11:28 UTC by jesusbv

The cloud provider info is set when updating
but not when registering for the first time.

2020-06-05 12:24 UTC, ikapelyukhin commented on lib/rmt.rb
> +  VERSION ||= '2.5.9'.freeze
2.5.9 is already taken in #569, please use 2.5.10 instead.

2020-06-05 22:28 UTC, ikapelyukhin commented
Oh, and package version in `package/obs/rmt-server.spec` also needs to be updated.
BTW, packaging documentation is in [PACKAGE.md](https://github.com/SUSE/rmt/blob/master/PACKAGE.md).

2021-01-28 13:56 UTC, thutterer commented
@jesusbv Hey, sorry this PR got no more feedback in such a long time! Are you still interested in getting this merged? There are a few conflicting files now, could you rebase your work on latest master, please? I then would take care that someone from the team reviews this. Thanks!

2021-04-14 13:58 UTC, digitaltom commented
@jesusbv please ping us if this pr is still wanted and needs review, so we can help you to get it released.

2021-04-15 10:26 UTC, jesusbv commented
> @jesusbv please ping us if this pr is still wanted and needs review, so we can help you to get it released.

Hi @digitaltom, yes I would say it is wanted, currently no cloud-provider info set when registering
thoughts?

2021-04-19 14:37 UTC, ngetahun commented
@jesusbv Please update the PR with the PULLREQUEST doc file in `.github`.

2021-04-19 14:38 UTC, ngetahun commented
@digitaltom Do we need to add a new db field for the registration proxy in scc to accomodate `cloud_provider` field?

2021-04-19 17:23 UTC, digitaltom commented
@ngetahun The cloud provider field is already there in RMT (https://github.com/SUSE/rmt/blob/master/db/schema.rb#L51) and SCC (https://github.com/SUSE/happy-customer/blob/master/glue/db/schema.rb#L111). 
I understand @jesusbv's description like this patch is fixing the setting of it during new registration, while it's already supported and works when a system updates it's hw_info.

2021-04-21 09:47 UTC, ngetahun requested changes

2021-04-21 09:47 UTC, ngetahun commented on lib/rmt.rb
> +  VERSION ||= '2.5.10'.freeze
@jesusbv The version bump is `2.5.9`.
```suggestion
  VERSION ||= '2.5.9'.freeze
```

2021-04-21 09:47 UTC, ngetahun commented on package/obs/rmt-server.changes
> +- Version 2.5.10
```suggestion
- Version 2.5.9
```

2021-04-26 12:15 UTC, ngetahun approved these changes
LGTM!

2021-04-26 12:16 UTC, merged