Contrib get repository tokens
SUSE/rmt pull request #716
Opened 2021-04-30 16:42 UTC by HaraldMuellerNey

## Description

Adding a small python script to get tokens via SCC API to setup custom repository.
The script requires user/password of the ORGA mirror credentials on command line.
You can provide various "strings" (URL Snippets).
For  each matching repository the scripts print one line providing:
_full url path,TOKEN_

Fixes # none

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ N/A] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [ N/A] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [N/A] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

2021-05-03 08:44 UTC, ngetahun requested changes

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +#!/usr/bin/env python
**Python2 EOL**

```suggestion
#!/usr/bin/env python3
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +                print repository['url'].split("?")[0]+","+repository['url'].split("?")[-1]
**Python2 EOL**
```suggestion
                print(repository['url'].split("?")[0]+","+repository['url'].split("?")[-1])
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +    print 'Usage:'
**Python2 EOL**

```suggestion
    print('Usage:')
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +    print '\t'+self+' -u <username> -o <password> <part of repository URL> [... <part of repository URL>]'
**Python2 EOL**

Usage instruction is wrong. The password flag needs to be `-p`.

```suggestion
    print('\t'+self+' -u <username> -p <password> <part of repository URL> [... <part of repository URL>]')
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +    print '\tUse the SCC mirror credentials of your organization for user and password'
**Python2 EOL**

```suggestion
    print('\tUse the SCC mirror credentials of your organization for user and password')
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +    print '\tProvide strings to match against repository URL'
**Python2 EOL**
```suggestion
    print('\tProvide strings to match against repository URL')
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +    print '\tThe script provides all matches, one per line, full URL and TOKEN separated by ",".'
**Python2 EOL**

```suggestion
    print('\tThe script provides all matches, one per line, full URL and TOKEN separated by ",".')
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +        print 'ERROR: missing user or password of your mirror credentials'
**Python2 EOL**
```suggestion
        print('ERROR: missing user or password of your mirror credentials')
```

2021-05-03 08:44 UTC, ngetahun commented on contrib/get_repository_tokens.py
> +        print 'ERROR: no strings to match against repository URL'
**Python2 EOL**
```suggestion
        print('ERROR: no strings to match against repository URL')
```

2021-05-03 15:06 UTC, ngetahun approved these changes

2021-05-06 14:44 UTC, Sergeykot commented
@HaraldMuellerNey @ngetahun should I merge and release it?

2021-05-07 22:29 UTC, HaraldMuellerNey commented
It is ready to merge from my end.

2021-05-10 12:05 UTC, ngetahun commented
@Sergeykot Can you hold off on the merge? We still need to release 2.6.9.

2021-05-18 06:36 UTC, Sergeykot commented
@ngetahun since we do not package the script we can merge it independently n the release.
@HaraldMuellerNey do you prefer this script to be in Python or we can also merge our Ruby port?

2021-05-18 06:56 UTC, HaraldMuellerNey commented
Feel free to convert it - I wrote it for myself and just thought it might be helpful for others.

2021-05-18 15:06 UTC, merged