WIP: Implements System-Token Validation
SUSE/rmt pull request #913
Opened 2022-07-12 17:31 UTC by lcaparroz

## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

2022-07-12 17:32 UTC, lcaparroz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[URAS] Add system token handling to RMT](https://trello.com/c/sB5sI7SC/2441-uras-add-system-token-handling-to-rmt)

2022-07-12 18:01 UTC, suse-tests-pass commented
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/261528/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8b1794885ba76229a5ecc6e5628a224b790c466d into 454855918e87bc5de7d526e497708e2e57e75488)

2022-07-14 09:28 UTC, suse-tests-pass commented
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/261802/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 722ee9d7f7b06772a10e05698093e34b37fe863c into 454855918e87bc5de7d526e497708e2e57e75488)

2022-07-14 09:51 UTC, suse-tests-pass commented
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/261803/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 92660a94e1fb93a6721125bc0165d6b5701b631e into 454855918e87bc5de7d526e497708e2e57e75488)

2022-07-20 14:03 UTC, ngetahun requested changes

2022-07-20 18:39 UTC, suse-tests-pass commented
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/262846/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 92660a94e1fb93a6721125bc0165d6b5701b631e into 71eecbdb59eda8f6be8d28244b7997e1bb6412c9)

2022-07-21 15:01 UTC, suse-tests-pass commented
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/262987/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04b5f713a3910fd1a419f7fda1a0641e6c91be62 into 71eecbdb59eda8f6be8d28244b7997e1bb6412c9)

2022-07-21 15:03 UTC, lcaparroz commented on spec/support/shared_examples/api_system_token.rb
> +shared_examples 'responds with a new token' do
Done at [d68a4bb](https://github.com/SUSE/rmt/pull/913/commits/d68a4bb8262ea474ad019039bc5b1252a89fa146).

2022-07-22 08:59 UTC, ngetahun approved these changes
LGTM!

2022-07-22 13:45 UTC, merged